export enum Step {
  DISABLE_STEPPERS = 3,
  COUNT_STEPS_X = 9,
  COUNT_STEPS_Y = 13,
  COUNT_STEPS_Z = 17,
  GET_STEPPER_STEPS_X = 6,
  GET_STEPPER_STEPS_Y = 10,
  GET_STEPPER_STEPS_Z = 14,
  STOP_MOTORS = 4,
  ZEROING_END = 2,
  ZEROING_END_X = 8,
  ZEROING_END_Y = 12,
  ZEROING_END_Z = 16,
  ZEROING_START = 1,
  ZEROING_START_X = 7,
  ZEROING_START_Y = 11,
  ZEROING_START_Z = 15,
}

export const SATAND_BY_MOTORS_SEQUENCE: Step[] = [
  Step.ZEROING_START,
  Step.DISABLE_STEPPERS,
];

export const WORKING_SPACE_X_SEQUENCE: Step[] = [
  Step.ZEROING_START_X,
  Step.COUNT_STEPS_X,
  Step.ZEROING_END_X,
  Step.GET_STEPPER_STEPS_X,
];

export const WORKING_SPACE_Y_SEQUENCE: Step[] = [
  Step.ZEROING_START_Y,
  Step.COUNT_STEPS_Y,
  Step.ZEROING_END_Y,
  Step.GET_STEPPER_STEPS_Y,
];

export const WORKING_SPACE_Z_SEQUENCE: Step[] = [
  Step.ZEROING_START_Z,
  Step.COUNT_STEPS_Z,
  Step.ZEROING_END_Z,
  Step.GET_STEPPER_STEPS_Z,
];
