export enum Step {
  COUNT_STEPS_X = 0,
  COUNT_STEPS_Y = 1,
  COUNT_STEPS_Z = 2,
  DISABLE_STEPPERS = 3,
  GET_STEPPER_STEPS_X = 4,
  GET_STEPPER_STEPS_Y = 5,
  GET_STEPPER_STEPS_Z = 6,
  SET_VALVE_1_OFF = 7,
  SET_VALVE_1_ON = 8,
  SET_VALVE_2_OFF = 9,
  SET_VALVE_2_ON = 10,
  STOP_MOTORS = 11,
  ZEROING_END = 12,
  ZEROING_END_S = 13,
  ZEROING_END_X = 14,
  ZEROING_END_Y = 15,
  ZEROING_END_Z = 16,
  ZEROING_START = 17,
  ZEROING_START_S = 18,
  ZEROING_START_X = 19,
  ZEROING_START_Y = 20,
  ZEROING_START_Z = 21,
}

export const SATAND_BY_MOTORS_SEQUENCE: Step[] = [
  Step.ZEROING_START,
  Step.DISABLE_STEPPERS,
];

export const WORKING_SPACE_X_SEQUENCE: Step[] = [
  Step.ZEROING_START_X,
  Step.COUNT_STEPS_X,
  Step.ZEROING_END_X,
  Step.GET_STEPPER_STEPS_X,
];

export const WORKING_SPACE_Y_SEQUENCE: Step[] = [
  Step.ZEROING_START_Y,
  Step.COUNT_STEPS_Y,
  Step.ZEROING_END_Y,
  Step.GET_STEPPER_STEPS_Y,
];

export const WORKING_SPACE_Z_SEQUENCE: Step[] = [
  Step.ZEROING_START_Z,
  Step.COUNT_STEPS_Z,
  Step.ZEROING_END_Z,
  Step.GET_STEPPER_STEPS_Z,
];

export const CLEAN_SEQUENCE: Step[] = [
  Step.SET_VALVE_1_ON,
  Step.ZEROING_END_S,
  Step.SET_VALVE_1_OFF,
  Step.ZEROING_START_S,
];
