export enum Step {
  COUNT_STEPS_X = 0,
  COUNT_STEPS_X_OFF = 1,
  COUNT_STEPS_Y = 2,
  COUNT_STEPS_Y_OFF = 3,
  COUNT_STEPS_Z = 4,
  COUNT_STEPS_Z_OFF = 5,
  DISABLE_STEPPERS = 6,
  GET_STEPPER_STEPS_X = 7,
  GET_STEPPER_STEPS_Y = 8,
  GET_STEPPER_STEPS_Z = 9,
  SET_VALVE_1_OFF = 10,
  SET_VALVE_1_ON = 11,
  SET_VALVE_2_OFF = 12,
  SET_VALVE_2_ON = 13,
  STOP_MOTORS = 14,
  ZEROING_END = 15,
  ZEROING_END_S = 16,
  ZEROING_END_X = 17,
  ZEROING_END_Y = 18,
  ZEROING_END_Z = 19,
  ZEROING_START = 20,
  ZEROING_START_S = 21,
  ZEROING_START_X = 22,
  ZEROING_START_Y = 23,
  ZEROING_START_Z = 24,
}

export const SATAND_BY_MOTORS_SEQUENCE: Step[] = [
  Step.ZEROING_START,
  Step.DISABLE_STEPPERS,
];

export const WORKING_SPACE_X_SEQUENCE: Step[] = [
  Step.ZEROING_START_X,
  Step.COUNT_STEPS_X,
  Step.ZEROING_END_X,
  Step.COUNT_STEPS_X_OFF,
  Step.GET_STEPPER_STEPS_X,
];

export const WORKING_SPACE_Y_SEQUENCE: Step[] = [
  Step.ZEROING_START_Y,
  Step.COUNT_STEPS_Y,
  Step.ZEROING_END_Y,
  Step.COUNT_STEPS_Y_OFF,
  Step.GET_STEPPER_STEPS_Y,
];

export const WORKING_SPACE_Z_SEQUENCE: Step[] = [
  Step.ZEROING_START_Z,
  Step.COUNT_STEPS_Z,
  Step.ZEROING_END_Z,
  Step.COUNT_STEPS_Z_OFF,
  Step.GET_STEPPER_STEPS_Z,
];

export const CLEAN_SEQUENCE: Step[] = [
  Step.SET_VALVE_1_ON,
  Step.ZEROING_END_S,
  Step.SET_VALVE_1_OFF,
  Step.ZEROING_START_S,
];
