import { type NextPage } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { io, type Socket } from "socket.io-client";

let socket: Socket;

const Home: NextPage = () => {
  const startSocket = async () => {
    await fetch("/api/socket");
    socket = io();

    socket.on("connect", () => {
      console.log("connected");
    });
  };

  useEffect(() => {
    void startSocket();
  }, []);

  const onOpen = () => {
    console.log("Open");
    socket.emit("blink", "open");
  };

  const onClose = () => {
    console.log("Close");
    socket.emit("blink", "close");
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            IST Project
          </h1>
          <div>
            <button
              className="border-2 border-solid p-2 text-black"
              onClick={() => {
                onOpen();
              }}
            >
              Open
            </button>
            <div className="w-4"></div>
            <button
              className="border-2 border-solid p-2 text-black"
              onClick={() => {
                onClose();
              }}
            >
              Close
            </button>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
